src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pzpn.Team.Web.Models
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [MinLength(6)]
        public string Password { get; set; }
    }
}

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Models/Players/PlayerListModel.cs
using System.Collections.Generic;

namespace Pzpn.Team.Web.Models.Players
{
    public class PlayerListModel
    {
        public IEnumerable<PlayerModel> Players { get; set; }
    }
}

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Models/Players/PlayerModel.cs
using System.ComponentModel.DataAnnotations;

namespace Pzpn.Team.Web.Models.Players
{
    public class PlayerModel
    {
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public uint Number { get; set; }
    }
}

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Controllers/AdvertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pzpn.Team.Web.Controllers
{
    public class AdvertController : Controller
    {

        // GET: Advert
        public ActionResult Display()
        {
            return PartialView();
        }
    }
}

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Controllers/HomeController.cs
using Pzpn.Team.Domain.Api.Services;
using Pzpn.Team.Web.Mappings;
using Pzpn.Team.Web.Models;
using Pzpn.Team.Web.Models.Players;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pzpn.Team.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPlayerService _playerService;
        private readonly IUserService _userService;
        private readonly Login _loginModel;

        public HomeController(IPlayerService playerService, IUserService userService)
        {
            _playerService = playerService;
            _userService = userService;
            _loginModel = new Login();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View(_loginModel);
        }

        [HttpPost]
        public ActionResult Login(Login loginModel)
        {
            
            if((ModelState.IsValid) && (_userService.CheckUser(loginModel.Email, loginModel.Password)))
                return RedirectToAction("Home");

            return View(loginModel);
        }


        public ActionResult Home()
        {
            PlayerListModel list = new PlayerListModel
            {
                Players = _playerService.GetAllTeam().Select(entity => PlayerMapper.ToModel(entity))
            };

            return View(list);
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Controllers/PlayerController.cs
using Pzpn.Team.Domain.Api.Services;
using Pzpn.Team.Domain.Services;
using Pzpn.Team.Web.Mappings;
using Pzpn.Team.Web.Models.Players;
using System.Linq;
using System.Web.Mvc;

namespace Pzpn.Team.Web.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerService _playerService;

        public PlayerController(IPlayerService playerService)
        {
            _playerService = playerService;
        }

        public ActionResult List()
        {
            PlayerListModel list = new PlayerListModel
            {
                Players = _playerService.GetAllTeam().Select(entity => PlayerMapper.ToModel(entity))
            };

            return View(list);
        }

        [ActionName("details")]
        public ActionResult DisplayPlayerDetails(uint number)
        {
            return View(PlayerMapper.ToModel(_playerService.GetPlayerByNumber(number)));
        }


        public ActionResult Players()
        {
            PlayerListModel list = new PlayerListModel
            {
                Players = _playerService.GetAllTeam().Select(entity => PlayerMapper.ToModel(entity))
            };

            return View(list);
        }

        [HttpGet]
        public ActionResult Edit(uint number)
        {
            ViewBag.ShouldAdvertsBeShown = true;

            return View(PlayerMapper.ToModel(_playerService.GetPlayerByNumber(number)));
        }   

        [HttpPost]
        public ActionResult Edit(uint number, PlayerModel player)
        {
            if (!ModelState.IsValid)
                return View(player);
            //todo validate model and save in db 


            return RedirectToAction("Edit", new { number = player.Number });
        }

    }
}

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Views/Home/Contact.cshtml
<div class="row">
    <div class="col-sm-8">
        <<h2> TEST TEST</h2>
        <h2> TEST TEST</h2>
    </div>
    <div class="col-sm-4">
    </div>
</div>

@section SiteName{

}

@section ViewName{
    To jest Contact Screen
}

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Views/Home/Home.cshtml
@model PlayerListModel

<div class="row">
    <div class="col-sm-6">
        <h2>To jest HomePage</h2>
        <h2>Mamy sobie: @Model.Players.Count() zawodników</h2>
    </div>
    <div class="col-sm-6">
        @Html.Action("Display","Advert")
    </div>
</div>


    @section SiteName{

    }

    @section ViewName{
        To jest Home Screen
    }

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Views/Home/Login.cshtml
@model Pzpn.Team.Web.Models.Login

<div class="row">
    <div>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary()

            <div>
                <h4>Tutaj Email</h4>
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>

            <div>
                <h4>Tutaj Hasło</h4>
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>

            <input type="submit" />
        }
    </div>
</div>

@section SiteName{

}

@section ViewName{
    To jest Login Screen
}

src/porowiec-michal/Pzpn.Team/Pzpn.Team.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="padding-top: 0px;">
    <div class="navbar navbar-inverse navbar-fixed-top" style="position: relative;">
        <div class="container">
            <h1>
                <span style="color: white">PZ</span><span style="color: red">PN</span>
            </h1>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Strona Startowa", "Home", "Home")</li>
                <li>@Html.ActionLink("Wszyscy Zawodnicy", "Players", "Player")</li>
                <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
            </ul>
            @RenderSection("SiteName")
        </div>
    </div>
    <div class="row"></div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Kamil Wołczyk</p> - @RenderSection("ViewName")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>